# Generated by Django 5.1.3 on 2024-12-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriveDunk', '0002_alter_usuario_options_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escuderia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='escuderias/')),
                ('numero_de_carreras', models.IntegerField()),
                ('escuderia', models.CharField(max_length=100)),
            ],
        ),
    ]
